/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection_LabelClips = new Collection({
    id: "pb_xvvovw30u1i3ew4",
    name: "LabelClips",
    type: "base",
    listRule: "@request.auth.id != \"\"",
    viewRule: "@request.auth.id != \"\"",
    createRule: "@request.auth.id != \"\"",
    updateRule: "@request.auth.id != \"\"",
    deleteRule: "@request.auth.id != \"\"",
    manageRule: null,
    fields: [
    {
      name: "id",
      type: "text",
      required: true,
      autogeneratePattern: "[a-z0-9]{15}",
      hidden: false,
      id: "text3208210256",
      max: 15,
      min: 15,
      pattern: "^[a-z0-9]+$",
      presentable: false,
      primaryKey: true,
      system: true,
    },
    {
      name: "created",
      type: "autodate",
      required: true,
      hidden: false,
      id: "autodate2990389176",
      onCreate: true,
      onUpdate: false,
      presentable: false,
      system: false,
    },
    {
      name: "updated",
      type: "autodate",
      required: true,
      hidden: false,
      id: "autodate3332085495",
      onCreate: true,
      onUpdate: true,
      presentable: false,
      system: false,
    },
    {
      name: "WorkspaceRef",
      type: "relation",
      required: true,
      collectionId: "pb_6znl9bq7apv0rcg",
      maxSelect: 1,
      minSelect: 0,
      cascadeDelete: false,
    },
    {
      name: "MediaRef",
      type: "relation",
      required: true,
      collectionId: "pb_1q5cu7dybj36pxm",
      maxSelect: 1,
      minSelect: 0,
      cascadeDelete: false,
    },
    {
      name: "TaskRef",
      type: "relation",
      required: false,
      collectionId: "pb_rm2tsf1ujhh49zr",
      maxSelect: 1,
      minSelect: 0,
      cascadeDelete: false,
    },
    {
      name: "labelType",
      type: "select",
      required: true,
      maxSelect: 1,
      values: ["object", "shot", "person", "speech"],
    },
    {
      name: "type",
      type: "text",
      required: true,
    },
    {
      name: "start",
      type: "number",
      required: false,
      min: 0,
    },
    {
      name: "end",
      type: "number",
      required: false,
      min: 0,
    },
    {
      name: "duration",
      type: "number",
      required: false,
      min: 0,
    },
    {
      name: "confidence",
      type: "number",
      required: false,
      min: 0,
      max: 1,
    },
    {
      name: "version",
      type: "number",
      required: false,
    },
    {
      name: "processor",
      type: "text",
      required: true,
    },
    {
      name: "provider",
      type: "select",
      required: true,
      maxSelect: 1,
      values: ["google_video_intelligence", "google_speech"],
    },
    {
      name: "labelData",
      type: "json",
      required: true,
    },
  ],
    indexes: [],
  });

  return app.save(collection_LabelClips);
}, (app) => {
  const collection_LabelClips = app.findCollectionByNameOrId("LabelClips");
  return app.delete(collection_LabelClips);
});
