/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection_LabelPerson = new Collection({
    id: "pb_3qcuf9dlte0h5l7",
    name: "LabelPerson",
    type: "base",
    listRule: "@request.auth.id != \"\"",
    viewRule: "@request.auth.id != \"\"",
    createRule: "@request.auth.id != \"\"",
    updateRule: "@request.auth.id != \"\"",
    deleteRule: "@request.auth.id != \"\"",
    manageRule: null,
    fields: [
    {
      name: "id",
      type: "text",
      required: true,
      autogeneratePattern: "[a-z0-9]{15}",
      hidden: false,
      id: "text3208210256",
      max: 15,
      min: 15,
      pattern: "^[a-z0-9]+$",
      presentable: false,
      primaryKey: true,
      system: true,
    },
    {
      name: "created",
      type: "autodate",
      required: true,
      hidden: false,
      id: "autodate2990389176",
      onCreate: true,
      onUpdate: false,
      presentable: false,
      system: false,
    },
    {
      name: "updated",
      type: "autodate",
      required: true,
      hidden: false,
      id: "autodate3332085495",
      onCreate: true,
      onUpdate: true,
      presentable: false,
      system: false,
    },
    {
      name: "WorkspaceRef",
      type: "relation",
      required: true,
      collectionId: "pb_6znl9bq7apv0rcg",
      maxSelect: 1,
      minSelect: 0,
      cascadeDelete: false,
    },
    {
      name: "MediaRef",
      type: "relation",
      required: true,
      collectionId: "pb_1q5cu7dybj36pxm",
      maxSelect: 1,
      minSelect: 0,
      cascadeDelete: false,
    },
    {
      name: "LabelEntityRef",
      type: "relation",
      required: true,
      collectionId: "pb_mo92djgubjkikt4",
      maxSelect: 1,
      minSelect: 0,
      cascadeDelete: false,
    },
    {
      name: "LabelTrackRef",
      type: "relation",
      required: true,
      collectionId: "pb_03xhgjzhymxc1pg",
      maxSelect: 1,
      minSelect: 0,
      cascadeDelete: false,
    },
    {
      name: "personId",
      type: "text",
      required: true,
    },
    {
      name: "personHash",
      type: "text",
      required: true,
      min: 1,
    },
    {
      name: "start",
      type: "number",
      required: false,
      min: 0,
    },
    {
      name: "end",
      type: "number",
      required: false,
      min: 0,
    },
    {
      name: "duration",
      type: "number",
      required: false,
      min: 0,
    },
    {
      name: "confidence",
      type: "number",
      required: false,
      min: 0,
      max: 1,
    },
    {
      name: "upperBodyColor",
      type: "text",
      required: false,
    },
    {
      name: "lowerBodyColor",
      type: "text",
      required: false,
    },
    {
      name: "hasLandmarks",
      type: "bool",
      required: false,
    },
    {
      name: "metadata",
      type: "json",
      required: true,
    },
  ],
    indexes: [
    "CREATE UNIQUE INDEX idx_label_person_hash ON LabelPerson (personHash)",
    "CREATE INDEX idx_label_person_workspace ON LabelPerson (WorkspaceRef)",
    "CREATE INDEX idx_label_person_media ON LabelPerson (MediaRef)",
    "CREATE INDEX idx_label_person_track ON LabelPerson (LabelTrackRef)",
  ],
  });

  return app.save(collection_LabelPerson);
}, (app) => {
  const collection_LabelPerson = app.findCollectionByNameOrId("LabelPerson");
  return app.delete(collection_LabelPerson);
});
