/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection_TimelineRecommendations = new Collection({
    id: "pb_91w0ka5joz10lay",
    name: "TimelineRecommendations",
    type: "base",
    listRule: "@request.auth.id != \"\"",
    viewRule: "@request.auth.id != \"\"",
    createRule: "@request.auth.id != \"\"",
    updateRule: "@request.auth.id != \"\"",
    deleteRule: "@request.auth.id != \"\"",
    manageRule: null,
    fields: [
    {
      name: "id",
      type: "text",
      required: true,
      autogeneratePattern: "[a-z0-9]{15}",
      hidden: false,
      id: "text3208210256",
      max: 15,
      min: 15,
      pattern: "^[a-z0-9]+$",
      presentable: false,
      primaryKey: true,
      system: true,
    },
    {
      name: "created",
      type: "autodate",
      required: true,
      hidden: false,
      id: "autodate2990389176",
      onCreate: true,
      onUpdate: false,
      presentable: false,
      system: false,
    },
    {
      name: "updated",
      type: "autodate",
      required: true,
      hidden: false,
      id: "autodate3332085495",
      onCreate: true,
      onUpdate: true,
      presentable: false,
      system: false,
    },
    {
      name: "WorkspaceRef",
      type: "relation",
      required: true,
      collectionId: "pb_6znl9bq7apv0rcg",
      maxSelect: 1,
      minSelect: 0,
      cascadeDelete: false,
    },
    {
      name: "TimelineRef",
      type: "relation",
      required: true,
      collectionId: "pb_8la546it5zge3cv",
      maxSelect: 1,
      minSelect: 0,
      cascadeDelete: false,
    },
    {
      name: "MediaClipRef",
      type: "relation",
      required: true,
      collectionId: "pb_v0io398cfx6qzc3",
      maxSelect: 1,
      minSelect: 0,
      cascadeDelete: false,
    },
    {
      name: "TimelineClipRef",
      type: "relation",
      required: false,
      collectionId: "pb_fb18j6mto8zli16",
      maxSelect: 1,
      minSelect: 0,
      cascadeDelete: false,
    },
    {
      name: "SeedClipRef",
      type: "relation",
      required: false,
      collectionId: "pb_fb18j6mto8zli16",
      maxSelect: 1,
      minSelect: 0,
      cascadeDelete: false,
    },
    {
      name: "score",
      type: "number",
      required: false,
      min: 0,
      max: 1,
    },
    {
      name: "rank",
      type: "number",
      required: false,
      min: 0,
    },
    {
      name: "reason",
      type: "text",
      required: true,
      min: 1,
      max: 500,
    },
    {
      name: "reasonData",
      type: "json",
      required: true,
    },
    {
      name: "strategy",
      type: "text",
      required: true,
    },
    {
      name: "targetMode",
      type: "text",
      required: true,
    },
    {
      name: "queryHash",
      type: "text",
      required: true,
      min: 1,
    },
    {
      name: "acceptedAt",
      type: "date",
      required: false,
    },
    {
      name: "dismissedAt",
      type: "date",
      required: false,
    },
    {
      name: "version",
      type: "number",
      required: false,
    },
    {
      name: "processor",
      type: "text",
      required: false,
    },
  ],
    indexes: [
    "CREATE UNIQUE INDEX idx_timeline_rec_hash_clip ON TimelineRecommendations (queryHash, MediaClipRef)",
    "CREATE INDEX idx_timeline_rec_context ON TimelineRecommendations (WorkspaceRef, TimelineRef, queryHash)",
    "CREATE INDEX idx_timeline_rec_rank ON TimelineRecommendations (queryHash, rank)",
    "CREATE INDEX idx_timeline_rec_feedback ON TimelineRecommendations (strategy, acceptedAt, dismissedAt)",
  ],
  });

  return app.save(collection_TimelineRecommendations);
}, (app) => {
  const collection_TimelineRecommendations = app.findCollectionByNameOrId("TimelineRecommendations");
  return app.delete(collection_TimelineRecommendations);
});
