# Tags and labels are injected at build time via additional bake files
# generated by docker/metadata-action; the placeholder tags below are only
# used when running `docker buildx bake` locally without those overlays.

variable "POCKETBASE_VERSION" {
  default = "0.39.4"
}

variable "NEXT_PUBLIC_POCKETBASE_URL" {
  default = "/"
}

# Comma-separated platform list. CI overrides this with a single native
# platform per runner (e.g. "linux/amd64") so nothing is built under QEMU.
variable "PLATFORM" {
  default = "linux/amd64,linux/arm64"
}

# GitHub Actions cache scope. CI sets a per-architecture scope so the two
# native runners don't clobber each other's cache.
variable "CACHE_SCOPE" {
  default = "videoware"
}

group "default" {
  targets = ["monolith", "worker", "webapp", "pocketbase"]
}

# Each app now has its own Dockerfile (docker/<app>.Dockerfile). They share a
# byte-identical base->deps->builder->runner-base prefix, so the GHA layer cache
# (mode=max, shared CACHE_SCOPE per arch) builds `yarn install` / the PocketBase
# download / the shared+app builds once and reuses them across all four targets.
target "_common" {
  context   = "."
  platforms = split(",", "${PLATFORM}")
  args = {
    POCKETBASE_VERSION         = "${POCKETBASE_VERSION}"
    NEXT_PUBLIC_POCKETBASE_URL = "${NEXT_PUBLIC_POCKETBASE_URL}"
  }
  cache-from = ["type=gha,scope=${CACHE_SCOPE}"]
  cache-to   = ["type=gha,mode=max,scope=${CACHE_SCOPE}"]
}

target "monolith" {
  inherits   = ["_common"]
  dockerfile = "docker/monolith.Dockerfile"
  target     = "monolith"
  tags       = ["videoware:local-monolith"]
}

target "worker" {
  inherits   = ["_common"]
  dockerfile = "docker/worker.Dockerfile"
  target     = "worker"
  tags       = ["videoware:local-worker"]
}

target "webapp" {
  inherits   = ["_common"]
  dockerfile = "docker/webapp.Dockerfile"
  target     = "webapp"
  tags       = ["videoware:local-webapp"]
}

target "pocketbase" {
  inherits   = ["_common"]
  dockerfile = "docker/pocketbase.Dockerfile"
  target     = "pocketbase"
  tags       = ["videoware:local-pocketbase"]
}
