# Tags and labels are injected at build time via additional bake files
# generated by docker/metadata-action; the placeholder tags below are only
# used when running `docker buildx bake` locally without those overlays.

variable "POCKETBASE_VERSION" {
  default = "0.35.0"
}

variable "NEXT_PUBLIC_POCKETBASE_URL" {
  default = "/"
}

group "default" {
  targets = ["monolith", "worker", "webapp", "pocketbase"]
}

target "_common" {
  context    = "."
  dockerfile = "docker/Dockerfile"
  platforms  = ["linux/amd64", "linux/arm64"]
  args = {
    POCKETBASE_VERSION         = "${POCKETBASE_VERSION}"
    NEXT_PUBLIC_POCKETBASE_URL = "${NEXT_PUBLIC_POCKETBASE_URL}"
  }
  cache-from = ["type=gha,scope=videoware"]
  cache-to   = ["type=gha,mode=max,scope=videoware"]
}

target "monolith" {
  inherits = ["_common"]
  target   = "monolith"
  tags     = ["videoware:local-monolith"]
}

target "worker" {
  inherits = ["_common"]
  target   = "worker"
  tags     = ["videoware:local-worker"]
}

target "webapp" {
  inherits = ["_common"]
  target   = "webapp"
  tags     = ["videoware:local-webapp"]
}

target "pocketbase" {
  inherits = ["_common"]
  target   = "pocketbase"
  tags     = ["videoware:local-pocketbase"]
}
