# Tags and labels are injected at build time via additional bake files
# generated by docker/metadata-action; the placeholder tags below are only
# used when running `docker buildx bake` locally without those overlays.

variable "POCKETBASE_VERSION" {
  default = "0.39.4"
}

variable "NEXT_PUBLIC_POCKETBASE_URL" {
  default = "/"
}

# Comma-separated platform list. CI overrides this with a single native
# platform per runner (e.g. "linux/amd64") so nothing is built under QEMU.
variable "PLATFORM" {
  default = "linux/amd64,linux/arm64"
}

# GitHub Actions cache scope. CI sets a per-architecture scope so the two
# native runners don't clobber each other's cache.
variable "CACHE_SCOPE" {
  default = "videoware"
}

group "default" {
  targets = ["monolith", "worker", "webapp", "pocketbase"]
}

target "_common" {
  context    = "."
  dockerfile = "docker/Dockerfile"
  platforms  = split(",", "${PLATFORM}")
  args = {
    POCKETBASE_VERSION         = "${POCKETBASE_VERSION}"
    NEXT_PUBLIC_POCKETBASE_URL = "${NEXT_PUBLIC_POCKETBASE_URL}"
  }
  cache-from = ["type=gha,scope=${CACHE_SCOPE}"]
  cache-to   = ["type=gha,mode=max,scope=${CACHE_SCOPE}"]
}

target "monolith" {
  inherits = ["_common"]
  target   = "monolith"
  tags     = ["videoware:local-monolith"]
}

target "worker" {
  inherits = ["_common"]
  target   = "worker"
  tags     = ["videoware:local-worker"]
}

target "webapp" {
  inherits = ["_common"]
  target   = "webapp"
  tags     = ["videoware:local-webapp"]
}

target "pocketbase" {
  inherits = ["_common"]
  target   = "pocketbase"
  tags     = ["videoware:local-pocketbase"]
}
