/**
 * Flow definition types for BullMQ FlowProducer
 * Shared across all flow builders
 */

import type { RenderStepType, DetectLabelsStepType } from '../types/step.types';
import type { ParentJobData } from '../types/job.types';
import type {
  TaskTranscodeInput,
  TranscodeStepType,
} from '@project/shared/jobs';

/**
 * Child job options
 */
export interface ChildJobOpts {
  attempts: number;
  backoff: {
    type: 'exponential';
    delay: number;
  };
  /** Fail this job's BullMQ parent immediately when this job fails. */
  failParentOnFailure?: boolean;
  /**
   * Let the BullMQ parent proceed even if this job fails (the failure is
   * still recorded on the failed job itself).
   */
  ignoreDependencyOnFailure?: boolean;
}

/**
 * Options for the flow's root (parent) job.
 * `jobId` is pre-generated by builders so child job data can carry a correct
 * `parentJobId` pointing at the flow root before the flow is added.
 */
export interface ParentJobOpts {
  jobId?: string;
  /** Override the queue's default retry count for the flow's root job. */
  attempts?: number;
}

// ============================================================================
// Transcode Flow Types
// ============================================================================

export interface TranscodeFlowDefinition {
  name: string;
  queueName: string;
  data: ParentJobData;
  opts?: ParentJobOpts;
  children: (TranscodeChildJobDefinition | FlowDefinition)[];
}

export interface TranscodeChildJobDefinition {
  name: TranscodeStepType;
  queueName: string;
  data: {
    taskId: string;
    workspaceId: string;
    stepType: TranscodeStepType;
    parentJobId: string;
    input: TaskTranscodeInput;
  };
  opts?: ChildJobOpts;
  children?: (TranscodeChildJobDefinition | FlowDefinition)[];
}

// ============================================================================
// Render Flow Types
// ============================================================================

export interface RenderFlowDefinition {
  name: string;
  queueName: string;
  data: ParentJobData;
  opts?: ParentJobOpts;
  children: (RenderChildJobDefinition | FlowDefinition)[];
}

export interface RenderChildJobDefinition {
  name: RenderStepType;
  queueName: string;
  data: {
    taskId: string;
    workspaceId: string;
    stepType: RenderStepType;
    parentJobId: string;
    input: unknown;
  };
  opts?: ChildJobOpts;
  children?: (RenderChildJobDefinition | FlowDefinition)[];
}

// ============================================================================
// Labels Flow Types
// ============================================================================

export interface LabelsFlowDefinition {
  name: string;
  queueName: string;
  data: ParentJobData;
  opts?: ParentJobOpts;
  children: (LabelsChildJobDefinition | FlowDefinition)[];
}

export interface LabelsChildJobDefinition {
  name: DetectLabelsStepType;
  queueName: string;
  data: {
    taskId: string;
    workspaceId: string;
    stepType: DetectLabelsStepType;
    parentJobId: string;
    input: unknown;
  };
  opts?: ChildJobOpts;
  children?: (LabelsChildJobDefinition | FlowDefinition)[];
}

// ============================================================================
// Union Types
// ============================================================================

export type FlowDefinition =
  | TranscodeFlowDefinition
  | RenderFlowDefinition
  | LabelsFlowDefinition;
