import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import reactHooks from "eslint-plugin-react-hooks";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Test files
    "**/__tests__/**",
    "**/*.test.{ts,tsx,js,jsx}",
    "**/*.spec.{ts,tsx,js,jsx}",
  ]),
  // Override rules
  {
    rules: {
      "@typescript-eslint/no-explicit-any": "warn",
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
        },
      ],
      // Adopt the compiler-aware Rules of React (eslint-plugin-react-hooks v7).
      // eslint-config-next already registers the plugin and enables the
      // `recommended` set; this opts into `recommended-latest`, which adds
      // checks for mutation-during-render and the other Rules-of-React
      // violations the older config skips.
      ...reactHooks.configs["recommended-latest"].rules,
      // Missing-dependency bugs should fail CI, not ship as warnings.
      "react-hooks/exhaustive-deps": "error",
      // Inline-constructed context provider values re-render every consumer on
      // every provider render — flag them so they get memoized.
      "react/jsx-no-constructed-context-values": "error",
    },
  },
  // Vendored shadcn/ui components are regenerated by the CLI, so we keep the
  // constructed-context-value rule as a non-blocking warning here rather than
  // editing generated code.
  {
    files: ["src/components/ui/**/*.{jsx,tsx}"],
    rules: {
      "react/jsx-no-constructed-context-values": "warn",
    },
  },
]);

export default eslintConfig;
